name: Pull Request Events

on: pull_request

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-check:
    name: Lint and check types
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: 📥 Download dependencies
        run: npm ci && cd functions && npm ci

      - name: 🧶 Lint
        run: npm run lint

      - name: 🧪 Check types
        run: npm run check

  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: 📥 Download dependencies
        run: npm ci && cd functions && npm ci

      - name: 🧪 Run tests
        run: npm test
